### ISSUE TITLE
feathers-sync couldnt understand mongodb+srv

### ISSUE THREAD

**Issue by msudgh** [feathersjs-ecosystem/feathers-sync#112]
I've tried to pass this connection string to sync package but its unable to understand mongodb connection string with `srv` and i think splitting connection string without at least using `indexOf` isn't enough.

https://github.com/feathersjs-ecosystem/feathers-sync/blob/e95a86643f9b42dc6f32004feab011607b791dab/lib/index.js#L24

example of mongodb+srv:

```
mongodb+srv://test:test@mongodb.net
```

result of these line codes:

```
const name = protocol.substring(0, protocol.length - 1); // 'mongodb+srv'
const adapter = mappings[name]; // undefined
```

**Comment by daffl** [comment]
If the protocol is not enough to determine the adapter you can use the alternative initialization API [documented here](https://github.com/feathersjs-ecosystem/feathers-sync#adapters):

```js
// Configure MongoDB with an existing connection
app.configure(sync.mongodb({
  db: config.uri,
  collection: 'events'
}));
```

**Comment by msudgh** [comment]
when we're designing a generic API it must have a bare configuration and not an advanced model. the current approach is mixed 🤦‍♂️.

**Comment by daffl** [comment]
A generic API needs to cover the 90% case in a generic way but still allow more advanced use cases which is what the adapter based approach of the design of this module is doing. Either way, this has been addressed now, thank you for the PR 😄
