### ISSUE TITLE
Multiple notifications while using amqp

### ISSUE THREAD

**Issue by gauravbhusare** [feathersjs-ecosystem/feathers-sync#120]
I configured sync in my feathers app.js as follows,

` app.configure(sync({
    uri: 'amqp://localhost'
  }));`

I have configured two instances of this same server

I placed a console in socket event of my feathers service as,

`  app.service('abc').on('created', data => {
    console.log("********************************************************************************");
  });`

Expected behavior is it should print console once on organization creation.

It is getting printed 3 to 4 times

**Comment by deskoh** [comment]
I can't seem to reproduce this. Works fine for me: https://github.com/deskoh/feathers-sync-test

**Comment by daffl** [comment]
I can't reproduce it as well. We can reopen with a a complete example to reproduce.
