### ISSUE TITLE
Using channels with feathers-sync

### ISSUE THREAD

**Issue by averri** [feathersjs-ecosystem/feathers-sync#132]
Broadcasting the events to all clients is not always desirable. `feathers-sync` should respect the channel configuration and publish/subscribe to the configured channels instead of broadcasting all the events to all clients.

**Comment by daffl** [comment]
This module is meant for server side for scaling/load balancing purposes. The channel system for connected clients still works the same even when using `feathers-sync` (if it doesn't this would be a bug of course).

**Comment by averri** [comment]
@daffl, thanks for informing that. But I still believe that using the channels information in `feathers-sync` would improve performance by having a optimized data transfer

Could you kindly check if this is a bug: https://github.com/feathersjs-ecosystem/feathers-sync/issues/131

I'm not able to use `feathers-sync` together with the following code:

```javascript
  // ISSUE: 'publish' is not a function
  app.service('session-manager').publish('created', ({sessionId}) => {
    return app.channel(sessionId)
  })
```

channels.js
```javascript
  app.on('login', (authResult, {connection}) => {

    if (connection) {
      // Obtain the logged in user from the connection
      const user = connection.user

      // NEW function to allow joining channels at service event handlers.
      // ISSUE: joinChannel is removed by feathers-sync. 
      connection.joinChannel = name => app.channel(name).join(connection)

      // NEW function to allow leaving channels at service event handlers.
      // ISSUE: leaveChannel is removed by feathers-sync.
      connection.leaveChannel = name => app.channel(name).leave(connection)

      // The connection is no longer anonymous, remove it
      app.channel('anonymous').leave(connection)

      // Add it to the authenticated user channel
      app.channel('authenticated').join(connection)

      app.channel(`users/${user.username}`).join(connection)
    }
  })
```

```javascript
  app.service('session-manager').on('created', (msg, ctx) => {
    let {connection} = ctx.params
    if(connection) {
      switch(msg.action) {
        case 'join':
          // ISSUE: feathers-sync removes the function from connection.
          connection.joinChannel(msg.sessionId)
          break
        case 'leave':
           // ISSUE: feathers-sync removes the function from connection.
          connection.leaveChannel(msg.sessionId)
          break
      }
    }
  })
```

**Comment by averri** [comment]
I have checked, and the channels filter is not working with feathers-sync. I have set the following configuration using Redis and feathers-sync:

- server: http://localhost:4000
  - logged users:
    - alex (joined channel 'team')
    - john (joined channel 'alone')

- server http://localhost:4001
  - logged users:
    - sara (joined channel 'team')

Configured the server to send all events only to the channel `team`:

```javascript
  app.publish((data, hook) => {
    return app.channel('team')
  })
```

But the users `alex` and `sara` receive events from `john`, who is in a different channel.

**Comment by averri** [comment]
Thanks @daffl, I was able to configure feathers-sync with Redis and SocketIO, it's working fine, but I had to overcome an issue with feathers-sync: if you add a new function property to the 'connection' object in the 'connection' event handler, feathers-sync will remove it. It's probably because some JSON.stringify.

My working demo: https://gitlab.com/averri/feathers-sync
