### ISSUE TITLE
Feather Context not updated on Horizontal scaling.

### ISSUE THREAD

**Issue by nithin-ideas2it** [feathersjs-ecosystem/feathers-sync#147]
### Steps to reproduce Issue
To scale the Feathers App, We introduced AWS load-balancer, Where Application1 and Appliation2, Both are same and which points to same DB(Mongo), Where in Application-1  the context updated is not reflected/updated to the context in the Application-2.

### System configuration

"node": "^8.0.0",
"@feathersjs/feathers": "3.3.1"

Need suggestion to fix the problem, should use 'feathers-redis-cache' or 'feathers-sync'? which is best solution for the problem?

Could someone help, to understand when to use  'feathers-redis-cache' and 'feathers-sync'?

**Comment by daffl** [comment]
You need to set up [feathers-sync](https://github.com/feathersjs-ecosystem/feathers-sync). It requires a running Redis or RabbitMQ instance. The setup and use-case is described in the Readme there.

**Comment by nithin-ideas2it** [comment]
Yes, I can use  feathers-sync to listen the changes as emitter on service events, but do feathers-sync will update the application context or we have to manually handle that? As I mentioned above, after update App1 will get the updated model in app.context, but App2 when trying to fetch the model in app.context  will get error error: MissingSchemaError: Schema hasn't been registered for model "modeltest".

So this case will be handled by feather with any config or we need have feathers-sync + manually handle to update the feathers app.context?
