### ISSUE TITLE
Only send sync events but not receive from other apps

### ISSUE THREAD

**Issue by apmcodes** [feathersjs-ecosystem/feathers-sync#148]
Currently, non-client facing apps receives sync events. Is there a way to configure such apps to only generate sync events but do not receive sync events.

Can this be accomplished via channel.js

```
    "@feathersjs/feathers": "^4.5.3",
    "@feathersjs/socketio": "^4.5.4",
    "feathers-sync": "^2.1.0",
```

**Comment by daffl** [comment]
You can probably just remove all `sync-in` event listeners after setting up `feathers-sync`:

```js
app.removeAllListeners('sync-in');
```

**Comment by apmcodes** [comment]
Got it. Thanks.
