### ISSUE TITLE
Update nats major version

### ISSUE THREAD

**Issue by daffl** [feathersjs-ecosystem/feathers-sync#163]
@ViljarVoidula kindly added nats support in #149 - recently the client version 2.0 has been released with a bunch of breaking changes [described in the migration guide](https://github.com/nats-io/nats.js/blob/master/migration.md).

**Comment by ViljarVoidula** [comment]
@daffl will try to find time upcoming week ^^

**Comment by daffl** [comment]
Closed via #175
