### ISSUE TITLE
Issue with Google oAuth

### ISSUE THREAD

**Issue by ericuldall** [feathersjs-ecosystem/feathers-sync#164]
### Steps to reproduce

I'm seeing some inconsistent behavior with google oauth using feathers-sync. 
Occasionally seeing the following error:
```
error=Grant%3A%20missing%20session%20or%20misconfigured%20provider
```

I'm wondering if the api for some reason start oauth in one instance and then redirects back to another instance?
Perhaps I need to also configure feathers http endpoint for sticky sessions to avoid any issues there?

**Comment by daffl** [comment]
Are you using Redis based sessions like [documented here](https://docs.feathersjs.com/api/authentication/oauth.html#setup-express)?

**Comment by ericuldall** [comment]
No :( Will that fix it? I have redis working for persisting events. Can I share the same instance?

**Comment by daffl** [comment]
Probably yes. And yes.

**Comment by ericuldall** [comment]
Okay. Rolling it out now :D Thanks @daffl

**Comment by ericuldall** [comment]
Works like a dream now <3
