### ISSUE TITLE
Custom events do not get broadcasted to other servers

### ISSUE THREAD

**Issue by sachinsawant71** [feathersjs-ecosystem/feathers-sync#173]
I have a feathersJS service with a custom event. I have two node cluster with feathers-sync, I am using rabbitMQ as a middleware for feathers-sync. 

When custom event is emitted on the first server, it is not received by second server. 

It works fine for standard event e.g. create, update etc.

**Module versions** 
"@feathersjs/feathers": "^4.3.1"
"feathers-sync": "2.4.0"

**NodeJS version**:
node version - v14.17.3

**Operating System**:
Linux

**Comment by daffl** [comment]
This is tested in https://github.com/feathersjs-ecosystem/feathers-sync/blob/release/test/core.test.js#L82 did you set it up as a custom event as described in https://docs.feathersjs.com/api/events.html#custom-events?
