### ISSUE TITLE
High RAM usage when large files are uploaded

### ISSUE THREAD

**Issue by roemhildtg** [feathersjs-ecosystem/feathers-sync#181]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

I am running a file service that has been sort of based off of the example file uploads in the feathers docs. When I upload a file that is fairly large ( > 100 MB ) the service starts using many GB of RAM and eventually crashes. Removing Feathers Sync from the app, the files are processed/uploaded immediately. 

Attached is my files service (with hooks): 

[files.zip](https://github.com/feathersjs-ecosystem/feathers-sync/files/8352284/files.zip)

Required config:

```yml
# config/default.yml
blobStore:
  type: local
  path: ../data
```

### Expected behavior

Feathers-sync shouldn't cause large amounts of RAM usage. I think there may be an issue with how the events are published with large files. 

### Actual behavior

I don't know exactly where the problem in this lies - it seems that when a request gets published that has a large file in it, the feathers-sync appears to use a lot of RAM. 

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
❯ npm ls feathers-sync
wsb-services-ts@1.16.2 /Users/groemhildt/projects/wsb-services-ts
└── feathers-sync@3.0.1

❯ npm ls @feathersjs/feathers
wsb-services-ts@1.16.2 /Users/groemhildt/projects/wsb-services-ts
├─┬ @feathersjs/authentication-client@4.5.13
│ └── @feathersjs/feathers@4.5.12 deduped

**NodeJS version**:
❯ node --version
v16.13.1

**Operating System**:
MacOS 12.2.1 Monteray

**Browser Version**:
Firefox 98.0.2

**Module Loader**:
webpack

**Comment by daffl** [comment]
You can [disable synchronization](https://github.com/feathersjs-ecosystem/feathers-sync#disabling-synchronization) for the `blob` service or set [context.event](https://docs.feathersjs.com/api/hooks.html#context-event) to `null` to emitting the event.

**Comment by roemhildtg** [comment]
Awesome. Yes that'll work for me. Thank you @daffl !
