### ISSUE TITLE
describe.only causing tests to be skipped

### ISSUE THREAD

**Issue by jamesholcomb** [feathersjs-ecosystem/feathers-sync#188]
https://github.com/feathersjs-ecosystem/feathers-sync/blame/622fbe28a13e1d2a29063762f83c377900e5e937/test/adapters/redis.test.js#L5

if I remove `.only`, then the test 'sends sync-out for custom events' fails:

`TypeError: Cannot read properties of undefined (reading 'toJSON')`

Updating the dev dep to @feathersjs/feathers@5.0.3 had no effect

P.S. This was after digging into why I could not get `sync` to work with an `ioredis` client (my app uses sentinels)

related

#186
#182

**Comment by daffl** [comment]
Good catch, thank you. The fix from #187 has been released as v3.0.3 and all tests are running now.
