### ISSUE TITLE
Pass a mongoDb Object as config.db

### ISSUE THREAD

**Issue by Jank1310** [feathersjs-ecosystem/feathers-sync#74]
I'm trying to use an existing mongodb connection but passing the db object in config won't work.

> db - The MongoDB connection string (e.g. mongodb://localhost:27017/events) or database object

Looking at the code (sync.js) it seems there is only connection string handling implemented...
One solution would be to just make the mongodb module importable or add database object handling.

Or did I miss something? :/

**Comment by daffl** [comment]
In the latest version, `db` does accept a MongoDB connection object like this:

```js
app.configure(sync.mongodb({
  db: existingConnection
  collection: 'events'
}));
```
