### ISSUE TITLE
Is serialization of the complete context required in event ?

### ISSUE THREAD

**Issue by claustres** [feathersjs-ecosystem/feathers-sync#87]
Starting from v1.0 not only the event data, but also the call context, is serialized as part of the event (at least for MongoDB, see https://github.com/feathersjs-ecosystem/feathers-sync/blob/master/lib/adapters/mongodb.js#L29). This already raised the following issue https://github.com/feathersjs-ecosystem/feathers-sync/issues/83, linked to the fact the context can be a really complex object structure not really suited for serialization. 

The "stringification" used to tackle this issue lead to data that are hard to read in the DB from a debug perspective. Moreover, only client data are really safe to be serialized IMHO. I wonder why the context serialization is actually required because from the client perspective only the data is sent back. I think removing it should avoid a lot of potential issues like performance overhead, failure to serialize cyclic JSON structures, etc.

**Comment by daffl** [comment]
People were expecting the hook context to be sent with service events. For example, `context.params.user` is pretty important for proper event dispatching.

**Comment by claustres** [comment]
For sure having event raised on the distant server with the same context as on the source server is great. However `params` is often used as a catch-all to store any information required by a service, e.g. it might hold some references to other services, internal objects, etc. making it not suitable for serialization IMHO (otherwise it should be clearly stated in the doc). Because `params` is not sent back to client I guess people usually do not clean it up after the service call, as I do I must confess 😄 

I wonder if at least it will be interesting to be able to set some "filtering" functions allowing to define what information is useful to be serialized. By default serializing only the user could be a relevant approach since it is the sole information really required by Feathers' core.

Otherwise do you recommend to create after hooks to clean the  `params` object before serialization ? It seems to me a little painful but should work since events are emitted after the hooks have been run if I am not wrong.

By the way I've also tried to prevent event emission in a service in V3 with `service.events = []` like it seemed to work in V2. However the events seem to be raised anyway, looking at the code I am a little confused by https://github.com/feathersjs/feathers/blob/master/packages/feathers/lib/events.js#L57. It looks like any event not managed at the service level is managed using a hook, it is not really clear how one can completely disable event emitting on a service.

Thanks for your answer.

**Comment by daffl** [comment]
I think this can now also be handled in v1.2.0 and later by using a [custom serializer/deserializer](https://github.com/feathersjs-ecosystem/feathers-sync#custom-serializer--deserializer).
